### ISSUE TITLE
Cannot access 'knex_mock_client_1' before initialization

### ISSUE THREAD

**Issue by brandon-burciaga** [felixmosh/knex-mock-client#47] opened 2023-09-30 15:39 UTC
Hey there. I am getting an error when trying to set up this library and use it in a test. 

`db-client.ts`
```
const DB = knex(config)
export default db
```

`my.test.ts`
```
import { createTracker, MockClient, Tracker } from 'knex-mock-client'

jest.mock('../../src/db-client', () => {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const knex = require('knex')
  return {
    db: knex({ client: MockClient }),
  }
})
```

Error:

```
ReferenceError: Cannot access 'knex_mock_client_1' before initialization                                                                                                                                                                    
```

Any ideas? Thank you!

**Comment by felixmosh** [comment] 2023-09-30 17:28
Hi,

Your code exports a default property, but your mock is mot, maybe this is related to that.

If this doesn't solves the issue, can you prepare a small reproduction repo?

**Comment by felixmosh** [comment] 2023-10-30 19:02
Ping?

**Comment by alessiomason** [comment] 2023-12-14 15:59
I genuinely have the same problem. Probably I just did not understand how to set it up. I would just like to be able to mock the values returned by the DB queries in order to test the logic of the application, I copied everything from your README but I still can't seem to get it to work.

The repository I'm working on is actually public, if you want to take a look at it. It's still early in development so I'm just trying out simple things.

[File in which I have the problem](https://github.com/alessiomason/gestionale/blob/main/server/tests/users.test.ts)

**Comment by felixmosh** [comment] 2023-12-14 19:14
> I genuinely have the same problem. Probably I just did not understand how to set it up. I would just like to be able to mock the values returned by the DB queries in order to test the logic of the application, I copied everything from your README but I still can't seem to get it to work.
> 
> The repository I'm working on is actually public, if you want to take a look at it. It's still early in development so I'm just trying out simple things.
> 
> [File in which I have the problem](https://github.com/alessiomason/gestionale/blob/main/server/tests/users.test.ts)

I'll check it out, thanx

**Comment by felixmosh** [comment] 2023-12-14 20:19
I've made a PR...
Looks like it is related to the fact that Jest started to hoist the mock block to be at the top, therefore, I've moved the MockClient import to be inside the mock block.

**Comment by alessiomason** [comment] 2023-12-16 10:42
Thank you so much! It works now, I've modified the other tests and written a few more.
Thanks for taking the time to take a look at it!

**Comment by felixmosh** [comment] 2023-12-16 10:59
Closing this issue, feel free to re-open if needed

**Closed by felixmosh** 2023-12-16 10:59 UTC
